### PR TITLE
Add the option to set a class to the global app wrapper

### PR DESCRIPTION
**Pull request by atomrc**
This allows to add a class to the div that wraps the whole app's DOM (for styling/positioning purposes)

### CODE REVIEW

**Comment by jvanbruegge** [comment]
A no brainer to merge.
I plan on rewriting this to remove a lot of pain points

**Comment by jvanbruegge** [comment]
Published as 5.1.0

**Comment by atomrc** [comment]
Wow, that was fast indeed !!!

Thanks Jan

**Comment by jvanbruegge** [comment]
No problem :)

**Pull request merged**
