### PR TITLE
chore(package.json): update package.json

### PR DESCRIPTION
**Pull request by FeliciousX**
TODO:

- [x] npm run build
- [x] npm run build:examples

### CODE REVIEW

**Comment by FeliciousX** [comment]
right now it fails on `npm run build`

```bash
> rimraf build/* && tsc -d --module ES6 --outDir build/es6 && tsc -d && rimraf build/examples

node_modules/cyclejs-utils/lib/es6/index.d.ts(2,27): error TS2307: Cannot find module 'cycle-onionify'.
src/modalify.ts(100,51): error TS2556: Expected 1-2 arguments, but got a minimum of 0.
```

**Comment by FeliciousX** [comment]
i've updated `cyclejs-utils` to latest.. but now  [this line](https://github.com/feliciousx-open-source/cyclejs-modal/blob/86f0d0c7ee1f55310b994d7a4c32d9b2edc34e69/src/modalify.ts#L100) is giving me a typescript error on `mergeSinks`
```javascript
modalStack$.map<Sinks>(arr => mergeSinks(...arr))
```
```bash
src/modalify.ts(100,51): error TS2556: Expected 1-2 arguments, but got a minimum of 0.
```

How do we fix this? @jvanbruegge 

it's because `mergeSinks` needs at least 1 arguments ( I think? ) but our `fold` for `modalStack$` starts with an empty array that gets spread out.. so 0 argument.

**Comment by jvanbruegge** [comment]
I had a breaking chang in `mergeSinks` it not takes an array as argument, forgot to update here

**Comment by FeliciousX** [comment]
hmm, what should I do to help?

**Comment by jvanbruegge** [comment]
So, I'm home again.
> hmm, what should I do to help?

Just replace `modalStack$.map<Sinks>(arr => mergeSinks(...arr))` with `modalStack$.map<Sinks>(mergeSinks)`
No need (aka, no possibility) to spread the array any more

**Comment by FeliciousX** [comment]
super sorry for the late response. fell sick over the weekend.

I've updated the branch with the latest fixes, it also broke at [this line](https://github.com/feliciousx-open-source/cyclejs-modal/blob/4c98764ec2bde648e0d453e3e1c9897964be1112/src/modalify.ts#L108) and fixed it assuming it's correct now?

:D 

P.S. The build for browserify is now broken since now build contains `cjs` and `es6` folder nested.

**Comment by FeliciousX** [comment]
nvm, fixed that too

**Comment by jvanbruegge** [comment]
Do the examples work again now?

**Comment by FeliciousX** [comment]
yes the examples work again!

**Comment by jvanbruegge** [comment]
Thanks! Will publish now

**Comment by jvanbruegge** [comment]
Published it as 5.0.0, because of the major version bump in cyclejs-utils, just to be save

**Pull request merged**
